(docs) Add messaging about the differences between this and the dsc modules
puppetlabs/puppetlabs-dsc_lite pull request #188
Opened 2022-01-24 21:30 UTC by binford2k

2022-01-24 21:51 UTC, michaeltlombardi requested changes
Some minor suggestions but this is A++ helping us move to more consistent/clear language.

2022-01-24 21:51 UTC, michaeltlombardi commented on README.md
> +***Using dsc_lite requires advanced experience with DSC and PowerShell, unlike our other modules that are far easier to use. It is an alternative approach to Puppet's family of [DSC modules](http://f
```suggestion
***Using dsc_lite requires advanced experience with DSC and PowerShell, unlike our other modules that are far easier to use. It is an alternative approach to Puppet's family of [DSC modules](http://forge.puppet.com/dsc), providing more flexibility for certain niche use cases. There are many drawbacks to this approach and we highly recommend that you use the existing family of [DSC modules](http://forge.puppet.com/dsc) instead, where possible.***
```

2022-01-24 21:51 UTC, michaeltlombardi commented on README.md
> +The `dsc_lite` module contains a lightweight `dsc` type, which a streamlined and minimal representation of a DSC Resource declaration in Puppet syntax. This type does not contain any DSC resources it
```suggestion
The `dsc_lite` module contains a lightweight `dsc` type, which is a streamlined and minimal representation of a DSC Resource declaration in Puppet syntax. This type does not contain any DSC resources itself, but can invoke arbitrary DSC Resources that already exist on the managed node. Much like the `exec` type, it simply passes parameters through to the underlying DSC Resource without any validation.
```

2022-01-24 21:51 UTC, michaeltlombardi commented on README.md
> +    * If you have custom DSC Resources, you can use the [Puppet.dsc module builder](https://github.com/puppetlabs/Puppet.Dsc) to build your own Puppet module from it.
```suggestion
You should *only* use the `dsc_lite` module when any of these cases apply to you:

* You need to use multiple versions of the same DSC resource
* The upstream DSC Resource's implementation does not match its declared API but is usable otherwise and needed.
  * In this case, `dsc_lite` should be treated as a stop-gap solution until the upstream DSC Resource can be patched to fix the misimplementation.
* You need to use a DSC Resource that isn't published to the [Puppet Forge](http://forge.puppet.com/dsc).
    * If you find a DSC Resource that hasn't been automatically imported, it's very likely due to the original DSC Resource failing schema validation. The `dsc_lite` module can get you by, but you should report the error upstream so that the original author can correct their code.
    * If you have custom DSC Resources, you can use the [Puppet.dsc module builder](https://github.com/puppetlabs/Puppet.Dsc) to build your own Puppet module from it.
```

2022-01-24 22:16 UTC, binford2k commented on README.md
> +    * If you have custom DSC Resources, you can use the [Puppet.dsc module builder](https://github.com/puppetlabs/Puppet.Dsc) to build your own Puppet module from it.
How would a user know about the API mismatch? I struggled with this a bit before settling on the "not on the forge" phrasing.

I suppose that if someone had the expertise to use dsc_lite, they'd know what that meant?

2022-01-25 01:36 UTC, michaeltlombardi commented on README.md
> +    * If you have custom DSC Resources, you can use the [Puppet.dsc module builder](https://github.com/puppetlabs/Puppet.Dsc) to build your own Puppet module from it.
Yeah, functionally, if you don't know what this means, you don't need to use `dsc_lite` to resolve it. This is a case where like the type does not correctly report itself even internally (ie the `Test` method is unreliable) or the API is mismatched.

2022-01-25 17:49 UTC, binford2k commented on README.md
> +    * If you find a DSC Resource that hasn't been automatically imported, it's very likely due to the original DSC Resource failing schema validation. The `dsc_lite` module can get you by, but you sh
```suggestion
    * If you find a DSC Resource that hasn't been automatically imported, it's very likely due to an API mismatch as described above.
```

2022-01-25 17:50 UTC, binford2k commented on README.md
> +    * If you find a DSC Resource that hasn't been automatically imported, it's very likely due to the original DSC Resource failing schema validation. The `dsc_lite` module can get you by, but you sh
@michaeltlombardi is this accurate?

2022-01-25 19:08 UTC, michaeltlombardi commented on README.md
> +    * If you find a DSC Resource that hasn't been automatically imported, it's very likely due to the original DSC Resource failing schema validation. The `dsc_lite` module can get you by, but you sh
yup!

2022-01-25 19:41 UTC, michaeltlombardi approved these changes

2022-01-25 19:42 UTC, merged